name: Build SmartStarter Jar
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21' }
      - uses: gradle/actions/setup-gradle@v4

      # settings.gradle(인코딩/저장소) 안전하게 작성
      - name: Write settings.gradle
        run: |
          cat > settings.gradle << 'EOF'
          pluginManagement {
            repositories {
              maven { url 'https://maven.fabricmc.net/' }
              gradlePluginPortal()
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
            repositories {
              mavenCentral()
              maven { url 'https://maven.fabricmc.net/' }
              maven { name 'Mojang'; url 'https://libraries.minecraft.net/' }
            }
          }
          rootProject.name = 'SmartStarter-1.21.6'
          EOF

      # build.gradle 보정: loom 버전/모장 저장소 보장
      - name: Patch build.gradle
        run: |
          sed -i "s/id[[:space:]]*['\"]fabric-loom['\"][[:space:]]*version[[:space:]]*['\"]1\.10['\"]/id 'fabric-loom' version '1.10.5'/" build.gradle || true
          grep -q "libraries.minecraft.net" build.gradle || \
            sed -i "0,/repositories[[:space:]]*{/s//repositories {\n    maven { name 'Mojang'; url 'https:\/\/libraries.minecraft.net\/' }/" build.gradle

      - name: Generate Wrapper
        run: gradle wrapper
      - name: Build
        run: ./gradlew --refresh-dependencies build
      - uses: actions/upload-artifact@v4
        with:
          name: SmartStarter-jar
          path: build/libs/*.jar
